name: New Software Feature
description: Describe a new feature request
title: "New Feature: "
labels: Analysis, Comment, Support, Support Ticket
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <img src=https://embention.com/files/Feature_Request.png alt="drawing" height="75"/>
        </p>
