name: Problem Report
description: Describe a Problem report
title: "[PR] : "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <img src=https://embention.com/files/PR.png alt="drawing" height="75"/>
        </p>

        <p align="center">
        <img src=https://embention.com/files/PR.png alt="drawing" height="75"/>
        </p>
        
- type: input
    id: Product
    attributes:
      label: "Product :"
      description: Please list all products involved.
      placeholder: 1xVeronte, CEX, PCS, SIL, ...
