name: New Software Feature
description: Describe a new feature request
title: "New Feature: "
labels: Analysis, Comment, Support, Support Ticket
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <img src=https://embention.com/files/PR.png alt="drawing" height="75"/>
        </p>

  - type: input
    id: Product
    attributes:
      label: "Product :"
      description: If applicable, please indicate the product for which the feature is being suggested
      placeholder: 1xVeronte, CEX, ...
