name: Onboarding Training
description: Onboarding Trainging
title: "[Onboarding] [Job] | "
labels: ["Analysis", "Comment", "RRHH"]
body:
  - type: markdown
    attributes:
      value: |
        ```
        Ejemplo:
        [Onboarding] [QAT] | 
        ```

  - type: input
    id: references
    attributes:
      label: References
      placeholder: "#1234"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        Hi!
        Congratulations on creating your first issue with us.
        Below you will find your first tasks. Please check them off once you have completed each one. We want to provide you with the initial training that will help you get up to speed within your team.
        Please note that most of our internal procedures are currently written in Spanish. If needed, you can use your browser’s Google Translate extension to review them in English.
        The same applies to YouTube training videos — please enable English subtitles when required.

  - type: checkboxes
    id: labels_assignees
    attributes:
      label: Labels & Assignees
      options:
        - label: I have assigned this issue to myself
        - label: I have added the department label related to my role to this issue
        - label: I have added the country label corresponding to my location

  - type: checkboxes
    id: introduction
    attributes:
      label: Introduction
      options:
        - label: Embention roadmap [URL](https://youtu.be/gqpAuGQw-kI)
        - label: Trade secret [URL](https://youtu.be/uZslY-fygBI?si=mYE-4RmySoslyDMF)
        - label: GitHub and SmartGit [URL](https://youtu.be/cNi-NjlZuKU?si=KoMj_pwABODoSjbV)

  - type: checkboxes
    id: general_procedures
    attributes:
      label: General Procedures
      options:
        - label: "P.058 - Welcome guideline [URL](https://documentation.embention.net/058/en/latest/)"
        - label: "P.030 - Internal and external communication [URL](https://documentation.embention.net/030/en/latest/index.html)"
        - label: "P.050 - Meetings [URL](https://documentation.embention.net/050/en/latest/)"
        - label: "P.195 - Odoo absences [URL](https://documentation.embention.net/195/en/latest/)"
        - label: "P.062 - Create issue [URL](https://documentation.embention.net/062/en/latest/)"
        - label: "P.072 - Timesheet entry [URL](https://documentation.embention.net/072/en/latest/)"
        - label: "P.541 - IT service request [URL](https://documentation.embention.net/541/en/latest/)"
        - label: "P.569 - Team skills management [URL](https://documentation.embention.net/569/en/latest/)"
        - label: "Reflect your skills in your employee profile"
        - label: "P.192 - Software tool management [URL](https://documentation.embention.net/192/en/latest/)"
        - label: "P.947- Standard operating procedure: corporate profile photography (mobile device) [URL](https://documentation.embention.net/947/en/latest/)"
        - label: "P.761 - Photo update [URL](https://documentation.embention.net/761/en/latest/)"
        - label: "Update your photo across our internal platforms."

  - type: checkboxes
    id: policies
    attributes:
      label: Policies
      options:
        - label: "PA.010 - Quality policy [URL](https://documentation.embention.net/010/en/latest/)"
        - label: "PA.196 - Data security guidelines [URL](https://documentation.embention.net/196/en/latest/)"
        - label: "PA.285 - Physical access Control Policy [URL](https://documentation.embention.net/285/en/latest/)"
        - label: "PA.287 - Access control policy [URL](https://documentation.embention.net/287/en/latest/)"
        - label: "PA.295 - Password policy [URL](https://documentation.embention.net/295/en/latest/)"
        - label: "PA.442 - Just culture policy [URL](https://documentation.embention.net/442/en/latest/)"
        - label: "PA.474 - Operational safety policy [URL](https://documentation.embention.net/474/en/latest/)"
        - label: "PA.544 - Trade secret policy [URL](https://documentation.embention.net/544/en/latest/)"
        - label: "PA.546 - Information asset usage policy [URL](https://documentation.embention.net/546/en/latest/)"
        - label: "PA.606 - Code of ethics and conduct [URL](https://documentation.embention.net/606/en/latest/)"
        - label: "P.805 - Harassment prevention and response protocol [URL](https://documentation.embention.net/805/en/latest/)"
        - label: "\"Acceptable use of assets policy\" questionnaire [URL](https://embention.net/survey/start/acceptable-use-of-assets-policy-28)"

  - type: checkboxes
    id: product_development
    attributes:
      label: Product Development (R&D)
      options:
        - label: "P.711 - Embention APQP [URL](https://documentation.embention.net/711/en/latest/index.html)"
        - label: "P.715 - APQP Process design & development [URL](https://documentation.embention.net/715/en/latest/index.html)"
        - label: "P.784 - APQP Planning procedure [URL](https://documentation.embention.net/784/en/latest/index.html)"

  - type: checkboxes
    id: ai_tools
    attributes:
      label: AI Tools
      options:
        - label: Training - AI tools [URL](https://embention.net/survey/start/training-ia-tools-1-0-79)
        - label: IA Agents - Embention [URL](https://sites.google.com/embention.com/internal-news/agentes-ia)
        - label: Kia-san - IA Tools [URL](https://notebooklm.google.com/)

  - type: textarea
    id: to_keep_in_mind
    attributes:
      label: To Keep in Mind
      value: |
        - All documentation is available at the following [link](https://embention.net/web#action=1236&model=emb.internal.document&view_type=list&menu_id=)
        - You can also access the **Documentation module directly from Odoo**, where all internal procedures and policies are centralized.
        - Most of our documentation is currently in Spanish. If needed, you can translate it directly in Chrome using the Google Translate browser extension.

  - type: textarea
    id: role_specific
    attributes:
      label: Role-Specific
      value: |
        - [ ] To be completed by your **Team Leader** and your **TPMO**. Please mention them here: @___________ & @___________
        - [ ] ...

  - type: textarea
    id: buddy_assignment
    attributes:
      label: Buddy Assignment
      value: |
        - [ ] To support you during your onboarding process, your **Team Leader** (please mention them here: @___________ ) will assign you a buddy.
        - **Assigned Buddy:** @____
        - Your buddy’s role will be:
            - Help you understand departmental processes and tools
            - Answer your more technical team-related questions
            - Provide general support during your adaptation period

  - type: textarea
    id: closing
    attributes:
      label: Closing
      value: |
        Don’t forget to close the issue once you’re done and feel free to reach out with any questions :)
        By closing the issue, we understand that you have reviewed and understood all the information provided above.

        Welcome!
