name: Onboarding Training
description: Plantilla para crear la issue inicial en el onboarding a la empresa
title: "[Onboarding Training] "
labels: ["Analysis","Comment"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Hola!

        Enhorabuena por crear tu primera issue con nosotros.

        Más abajo encontrarás también tus primeras tareas, haz check cuando hayas finalizado cada una de ellas.

        Queremos acercarte la formación inicial que te ayudará a desenvolverte en nuestro equipo y también queremos proponerte una actividad para entrar en contacto con las herramientas que emplearás en tu día a día.

        > [!IMPORTANT]
        > Te propondremos que modifiques algún procedimiento (que corrijas un error que detectes o que propongas una mejora) por lo que te pedimos que prestes especial atención.

        **FORMACIÓN**
  - type: checkboxes
    attributes:
      label: Material multimedia
      options:
        - label: Bienvenida [URL](https://drive.google.com/file/d/17rJrvYWgvFT0cBqS6eCbGH8CpS76yyPD/view?usp=drive_link)
        - label: Roadmap Embention [URL](https://drive.google.com/file/d/1GM4ynrD6R87hqdgRBWcpEEsSAurp6CDS/view?usp=drive_link)
        - label: Sensibilización en ISO 9001 [URL](https://drive.google.com/file/d/1GM4ynrD6R87hqdgRBWcpEEsSAurp6CDS/view?usp=drive_link)
        - label: Secreto empresarial [URL](https://drive.google.com/file/d/1bhyjMC4GKeAp6zm1PI_J9Q2yqmk7FoJa/view?usp=drive_link)
        - label: Github y Smartgit [URL](https://drive.google.com/file/d/121jy3fmvEM1cHfEu7R7Qkr7XXPsZk53g/view?usp=drive_linkusp=drive_link)
  - type: markdown
    attributes:
      value: |
        - Todos los procedimientos se encuentran en: [Procedimientos] (https://embention.net/web#action=1236&model=emb.internal.document&view_type=list&menu_id=)
  - type: checkboxes
    attributes:
      label: Procedimientos
      options:
        - label: P.058-pauta-de-bienvenida [URL](https://documentation.embention.net/058/es/latest/index.html)