name: Onboarding Training
description: Plantilla para crear la issue inicial en el onboarding a la empresa
title: "[Onboarding Training] "
labels: ["Analysis","Comment"]
body:
  - type: textarea
    id: refrences
    attributes:
      label: References
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: formacion
    attributes:
      label: Plan de formación
      value: |
        # Formación
  - type: checkboxes
    attributes:
      label: Introducción
      options:
        - label: Bienvenida [URL](https://drive.google.com/file/d/17rJrvYWgvFT0cBqS6eCbGH8CpS76yyPD/view?usp=drive_link)
        - label: Roadmap Embention [URL](https://drive.google.com/file/d/1GM4ynrD6R87hqdgRBWcpEEsSAurp6CDS/view?usp=drive_link)
        - label: Sensibilización en ISO 9001 [URL](https://drive.google.com/file/d/1YVMmp4uhIxBZ-orWx4QaYRpAVqYozoe0/view?usp=drive_link)
        - label: Secreto empresarial [URL](https://drive.google.com/file/d/1bhyjMC4GKeAp6zm1PI_J9Q2yqmk7FoJa/view?usp=drive_link)
        - label: Github y Smartgit [URL](https://drive.google.com/file/d/121jy3fmvEM1cHfEu7R7Qkr7XXPsZk53g/view?usp=drive_linkusp=drive_link)
  - type: textarea
    id: procedures
    attributes:
      label: Procedimientos Generales
      value: |
        - Todos los procedimientos se encuentran en: [Procedimientos](https://embention.net/web#action=1236&model=emb.internal.document&view_type=list&menu_id=)
  - type: checkboxes
    attributes:
      label: Listado procedimientos
      options:
        - label: P.058 - Pauta de bienvenida [URL](https://documentation.embention.net/058/es/latest/index.html)
        - label: P.030 - Comunicacion interna y externa [URL](https://documentation.embention.net/030/es/latest/index.html)
        - label: P.050 - Reuniones [URL](https://documentation.embention.net/050/es/latest/index.html)
        - label: P.190 - Dia de-concentracion teletrabajo opcional [URL](https://documentation.embention.net/190/es/latest/index.html)
        - label: P.195 - Ausencias odoo [URL](https://documentation.embention.net/195/es/latest/index.html)
        - label: P.257 - Apertura automatica de puertas [URL](https://documentation.embention.net/257/es/latest/index.html)
        - label: P.389 - Semana intensiva opcional [URL](https://documentation.embention.net/389/es/latest/index.html)
        - label: P.398 - Preguntas frecuentes RRHH [URL](https://documentation.embention.net/398/es/latest/index.html)
        - label: P.062 - Crear issue [URL](https://documentation.embention.net/062/es/latest/index.html)
        - label: P.072 - Carga de horas timesheets [URL](https://documentation.embention.net/072/es/latest/index.html)
        - label: P.541 - Solicitud de servicios IT [URL](https://documentation.embention.net/541/es/latest/index.html)
        - label: P.569 - Gestión de Skills del equipo [URL](https://documentation.embention.net/569/es/latest/index.html)
        - label: Refleja tus skills de tu ficha empleado
        - label: P.441 - Plan de evacuación de incendios [URL](https://documentation.embention.net/441/es/latest/index.html)
  - type: textarea
    id: policies
    attributes:
      label: Políticas
      value: |
        - Todos las políticas se encuentran en: [Políticas](https://embention.net/web#action=1236&model=emb.internal.document&view_type=list&menu_id=)
  - type: checkboxes
    attributes:
      label: Listado políticas
      options:
        - label: PA.010 - Politica de Calidad [URL](https://documentation.embention.net/010/en/latest/index.html)
        - label: PA.196 - Directrices de Seguridad de la Informacion [URL](https://documentation.embention.net/196/es/latest/index.html)
        - label: PA.285 - Política de control de acceso físico [URL](https://documentation.embention.net/285/es/latest/index.html)
        - label: PA.287 - Politica de control de acceso [URL](https://documentation.embention.net/287/es/latest/index.html)
        - label: PA.295 - Politica de contraseñas [URL](https://documentation.embention.net/295/es/latest/index.html)
        - label: PA.442 - Politica de cultura justa [URL](https://documentation.embention.net/442/es/latest/index.html)
        - label: PA.474 - Politica seguridad operacional [URL](https://documentation.embention.net/474/es/latest/index.html)
        - label: PA.544 - Politica de secreto empresarial [URL](https://documentation.embention.net/544/es/latest/index.html)
        - label: PA.546 - Politica de uso de activos de informacion [URL](https://documentation.embention.net/546/es/latest/index.html)
        - label: Cuestionario "Acceptable Uso of Assets Policy" [URL](https://embention.net/survey/start/acceptable-use-of-assets-policy-28)
        - label: Cuestionario "Awareness Survey ISO 9001:2015 and EN 9100:2018" [URL](https://embention.net/survey/start/awareness-survey-iso-9001-2015-and-en-9100-2018-29)
  - type: textarea
    id: opcionales
    attributes:
      label: Opcionales
      value: |
        - También te acercamos al Roadmap de Embention [URL](https://drive.google.com/file/d/1GM4ynrD6R87hqdgRBWcpEEsSAurp6CDS/view?usp=drive_link)
  - type: textarea
    id: departmentProcedures
    attributes:
      label: Específicas del puesto
      value: |
        - [ ] Listado a rellenar por parte de tu team leader. Menciónalo aquí ________ para que le llegue la notificación.
          - [ ] ....
          
        No olvides cerrar la issue cuando acabes ni de consultarnos todas tus dudas :)
        
        ¡Bienvenido/a!
