name: Problem Report
description: Describe a Problem report
title: "[PR]: "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        We're sorry that you have encountered an issue with one of our products.
        Please fill the following template in as much detail as possible so we can better aid you in solving this.
  - type: markdown
    attributes:
      value: |
        # Hardware Description
  - type: dropdown
    id: Hardware
    attributes:
      label: "Product: "
      description: Select all Products which were involved during the issue.
      multiple: true
      options:
        - 1xVeronte Autopilot
        - 4xVeronte Autopilot
        - SIL
        - BCS
        - PCS
        - MCS
        - Gimbal Camera
        - Tracking Antenna
        - BEC
        - CEX
        - MEX
        - Veronte Stick Expander
        - MC01
        - MC110
        - MC24
        - Other
  - type: input
    id: Serial_Num
    attributes:
      label: "Serial Number: "
      description: Please specify the Serial Number of all of the products selected above.
      placeholder: 1xVeronte SN 4041, CEX SN 1500, ...
  - type: markdown
    attributes:
      value: |
        # Firmware Description
  - type: input
    id: Fw_num
    attributes:
      label: "Firmware Version: "
      description: Please specify the Firmware Version for all of the products selected above.
      placeholder: 1xVeronte 6.12.68, CEX 6.12.60, ...
  - type: markdown
    attributes:
      value: |
        # Software Description
  - type: dropdown
    id: APP
    attributes:
      label: "Apps: "
      description: What App are you seeing the problem on?
      multiple: true
      options:
        - VeronteLink
        - VeronteHIL
        - VeronteOps
        - VeronteFDR
        - VeronteUpdater
        - 1x PDIBuilder
        - 1x PDICalibration
        - 1x PDITuning
        - 4x PDIBuilder
        - BCS PDIBuilder
        - Gimbal Studio
        - CEX PDIBuilder
        - MEX PDIBuilder
        - VSE Application
        - MC01B PDIBuilder
        - MC01S PDIBuilder
        - MC110 PDIBuilder
        - Other
  - type: input
    id: Software_version
    attributes:
      label: "App version: "
      description: Please specify the version of all of the Apps selected above.
      placeholder: VeronteLink 6.12.22, 1xVerontePDIBuilder 6.12.44, ...
  - type: markdown
    attributes:
      value: |
        # Configuration Files
  - type: textarea
    id: Config_Files
    attributes:
      label: "Configuration files: "
      description: If apply, Attach a .zip file for the configurations
  - type: markdown
    attributes:
      value: |
        # Problem Description
  - type: textarea
    id: Problem_Description
    attributes:
      label: "Problem Description: "
      description: Problem/bug description
  - type: textarea
    id: Steps_reproduce
    attributes:
      label: "Steps to reproduce: "
      description: If known, details to reproduce the failure, URLs, screenShoots, Traceback errors, printed errors, ...
  - type: markdown
    attributes:
      value: |
        -----
        Thank you for taking this time to report it.
        ![Embention_Logo](https://www.embention.com/wp-content/webp-express/webp-images/doc-root/wp-content/themes/embention/images/header-logo-embention.png.webp)
