name: Problem Report
description: Describe a Problem report
title: "[PR]: "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > "### We're sorry that you have encountered an issue with one of our products."
  - type: markdown
    attributes:
    value: |
      > [!TIP]
      > "### Please provide as much information as possible to better identify where the problem might originate from"
  - type: markdown
    attributes:
      value: |
        ----
  - type: markdown
    attributes:
      value: |
        "# Product Description"
  - type: input
    id: Product
    attributes:
      label: "Product: "
      description: Please write about all products involved.
      placeholder: 1xVeronte, CEX, PCS, SIL, ...
