name: Problem Report
description: Describe a Problem report
title: "[PR]: "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        <h1 align="center"><ins>Embention Problem Report Form</ins></h1>
        
        &#8192;
        &#8192;
        ### We sincerely apologize for any inconvenience caused by the encountered issue and extend our gratitude for bringing it to our attention.
        &#8192;
        > [!TIP]
        > ### Please provide as much information as possible to better identify where the problem might originate from
        <br/><br/>

  - type: markdown
    attributes:
      value: |
        # Product Description
  - type: input
    id: Product
    attributes:
      label: "Product: "
      description: Please write about all products involved.
      placeholder: 1xVeronte, CEX, PCS, SIL, ...
  - type: input
    id: hw_Serial_Num
    attributes:
      label: "Serial Number: "
      description: Please in the same order specify the Serial Number of all of the products from above.
      placeholder: 1xVeronte SN 4041, CEX SN 1500, ...
  - type: markdown
    attributes:
      value: |
        ----
  - type: markdown
    attributes:
      value: |
        # Firmware Description
  - type: input
    id: Fw_version
    attributes:
      label: "Firmware Version: "
      description: Please specify the Firmware Version for all of the products selected above.
      placeholder: 1xVeronte 6.12.68, CEX 6.12.60, ...
  - type: markdown
    attributes:
      value: |
        ----
  - type: markdown
    attributes:
      value: |
        # Software Description
  - type: input
    id: App_ver
    attributes:
      label: "Apps Version: "
      description: Please specify the Applications involved.
      placeholder: 1xVerontePDIBuilder, VeronteLink, VeronteOps, ...
  - type: input
    id: Software_version
    attributes:
      label: "App version: "
      description: Please specify the version of all of the Apps selected above.
      placeholder: 1xVerontePDIBuilder 6.12.54, VeronteLink 6.12.22, VeronteOps 6.12.34, ...
  - type: markdown
    attributes:
      value: |
        ----
  - type: markdown
    attributes:
      value: |
        # Configuration Files
  - type: textarea
    id: Config_Files
    attributes:
      label: "Configuration files: "
      description: Please attach a .zip file for the related configurations.
  - type: markdown
    attributes:
      value: |
        ----
  - type: markdown
    attributes:
      value: |
        # Problem Description
  - type: textarea
    id: Problem_Description
    attributes:
      label: "Problem Description: "
      description: Describe in as much detail the problem encountered.
  - type: textarea
    id: Steps_reproduce
    attributes:
      label: "Steps to reproduce: "
      description: If known, detail the steps to reproduce the problem. Provide screenshots, Error codes, Link Session files, ...
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > ### Thank you for taking this time to report it.
        <p align="center">
        <img src="https://www.embention.com/files/firma-embention.png" alt="drawing" width="1080"/>
        </p>
