name: Problem Report
description: Describe a Problem report
title: "[PR]: "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        "# Product Description"
  - type: input
    id: Product
    attributes:
      label: "Product: "
      description: Please write about all products involved.
      placeholder: 1xVeronte, CEX, PCS, SIL, ...
