name: Problem Report
description: Describe a Problem report
title: "[PR]: "
labels: Analysis, Comment, PR, Support
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > "### We're sorry that you have encountered an issue with one of our products."
