name: Purchases Template
description: Request a Purchase
title: "[Solicitud de compra] "
labels: ["Analysis","Comment","Purchases"]
body:
  - type: input
    id: reference
    attributes:
      label: Internal Reference
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Product description
      value: | Campo | Detallar |
                    | --- | --- |
                    | **Ref.Int.** | ... |
                    | **Descripción :exclamation:** | ... | 
                    | **Familia :grey_exclamation:** | ... | 
                    | **Esp.Requeridas :grey_exclamation:**  | ... | 
                    | **Proy./Dpto :exclamation:** | ... | 
                    | **Cantidad :exclamation:** | 1 centralita y diría que 7 cámaras | 
                    | **Plazo :exclamation:** | ... |
                    | **Es el repuesto de un componente dañado (si/no):exclamation:** | ... |
    validations:
      required: true
  - type: input
    id: department
    attributes:
      label: Project/Department
    validations:
      required: true
  - type: input
    id: quantity
    attributes:
      label: Quantity
    validations:
      required: true
  - type: input
    attributes:
      label: Analytic Account
    validations:
      required: true
  - type: input
    attributes:
      label: Analytic Tags
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Deadline
      multiple: false
      options:
        - No time
        - ASAP
        - 1 week
        - 2 weeks
        - 1 month
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Replacement of damaged component
      description: Check if it's a replacement of damaged component
      options:
        - label: Replacement?
