name: RMA #####
description: Start an RMA process
title: "RMA"
labels: Analysis, Comment, Support, Support Ticket
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <img src=https://embention.com/files/sp_RMA.png alt="drawing" height="75"/>
        </p>
        
        <p align="center">
        <h4>
        This issue will start an RMA process for an Embention product.</br>
        </h4>
        </p>
        
        > [!IMPORTANT]
        > ### First of all, please make sure that someone from the support team has confirmed that an RMA is needed for one of your units.

        <h4>
        
        Steps:</br>
        1. Download and fill the following <a href="https://github.com/embention/PDITemplates/files/13176415/F.449.03.-.RMA.template.pdf">form</a>.</br>
        2. Attach the form to the text area below.</br>
        3. Embention Staff will provide an RMA number and update the form.</br>
        4. Ship the unit following the guidance on the form.</br>
        
        </h4>
        <br></br>
        
  - type: textarea
    attributes:
      label: Attach bwlow
      placeholder: "Upload here the filled in RMA Template"
