name: Support Ticket
description: General question
labels: Analysis, Comment, Support, Support Ticket
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <img src=https://embention.com/files/Support_Ticket.png alt="drawing" height="75"/>
        <br><br/>
        </p>

        This opens a Support Ticket for general queries or discussions regarding the Embention products. Public information can be found on our online manuals.
        
        > [!TIP]
        > ### Please check out our online manuals at https://manuals.embention.com/ in case your question is already addressed there.

        > [!WARNING]
        > ### Specific support integration of peripherals, wiring diagrams, or any dedicated work requires the use of Support Hours which can be purchased by contacting sales@embention.com.        
        
        <p align="center">
        <br><br/>
        </p>

  - type: markdown
    attributes:
      value: |
        <h1 align="center">Product Description</h1>
        
  - type: input
    id: Product
    attributes:
      label: "Product :"
      description: If applicable, please list all products involved and their Serial Numbers.
      placeholder: 1xVeronte SN 4041, CEX SN 1500, ...
  
  - type: input
    id: Fw_version
    attributes:
      label: "Firmware Version: "
      description: If applicable, please specify the Firmware Version for all of the products described above.
      placeholder: 1xVeronte 6.12.68, CEX 6.12.60, ...
  
  - type: input
    id: App_ver
    attributes:
      label: "Apps: "
      description: If applicable, please specify the Applications involved and their version.
      placeholder: 1xVerontePDIBuilder 6.12.54, VeronteLink 6.12.22, VeronteOps 6.12.34, ...
  
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <br/>
        </p>
  
  - type: markdown
    attributes:
      value: |
        <h1 align="center">Configuration Files</h1>
  
  - type: textarea
    id: Config_Files
    attributes:
      label: "Configuration files: "
      description: If applicable, please attach a .zip file with the related PDI configuration.
  
  - type: markdown
    attributes:
      value: |
        <p align="center">
        <br/>
        </p>
  
  - type: markdown
    attributes:
      value: |
        <h1 align="center">Description</h1>
  
  - type: textarea
    id: Description
    attributes:
      label: "Support Ticket description"
      description: A concise description of the general support needed.


