name: Project automations done
on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - labeled
  issue_comment:
    types: created
env:
  todo: Todo
  done: Done
  in_progress: In Progress
  ans: Answered
  not_ans: Not Answered
  organization: dev-embention
  project: 2
  REPO_TITLE: ${{ github.repository }}
  ISSUE_TITLE: "${{ github.event.issue.title }}"

jobs:
  issue_done:
    name: issue_done
    runs-on: ubuntu-latest
    steps:
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: github.event.action == 'labeled' && github.event.label.name == 'Stale'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
