name: Project automations done
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_TOKEN_MOVE_ISSUES }}"
        project-url: "https://github.com/orgs/dev-embention/projects/2"
        column-name: "Done"
        label-name: "Stale"
        columns-to-ignore: "Answered,Not Answered,Close"