name: Generate EMD Preview

on:
    push:

jobs:
  generate-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call API to Generate Preview
        env:
          EMD_API_HOST: ${{ vars.EMD_API_HOST }}
          EMD_API_KEY: ${{ secrets.JOB_EMD_API_KEY }}
        #   REPO_URL: "${{ github.server_url }}/${{ github.repository }}"

        run: |
          REF="release/MD-186/es/014"
          echo "Ref: $REF"
          DOC_PATH="docs/procedures/MD-P.186-edicion-de-documentacion"
          REPO_URL="https://github.com/dev-embention/poc-embention-tools-1177"
          echo "Repo URL: $REPO_URL"

            response=$(curl -X POST "${EMD_API_HOST}/api/v1/doc/preview" \
              -H "accept: application/json" \
              -H "X-API-KEY: ${EMD_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "{\"doc_path\": \"$DOC_PATH\", \"lang\": \"es\", \"ref\": \"$REF\", \"repo_url\": \"$REPO_URL\"}")

            echo "Response Code: $response"

      - name: Debug API Request
        run: |
          echo "curl -X POST \"${EMD_API_HOST}/api/v1/doc/preview\" \\
              -H \"accept: application/json\" \\
              -H \"X-API-KEY: ${EMD_API_KEY}\" \\
              -H \"Content-Type: application/json\" \\
              -d '{\"doc_path\": \"${DOC_PATH}\", \"lang\": \"es\", \"ref\": \"$REF\", \"repo_url\": \"$REPO_URL\"}'"
