name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  issue_comment:
    types: created
  schedule:
    - cron: '40 15 * * *'

# map fields with customized labels
env:
  todo: Todo
  done: Done
  in_progress: In Progress
  ans: Answered
  not_ans: Not Answered
  organization: dev-embention
  project: 2
  REPO_TITLE: ${{ github.repository }}
  ISSUE_TITLE: "${{ github.event.issue.title }}"
  
jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }} # New issues
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          #user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  issue_done:
    name: issue_done
    runs-on: ubuntu-latest
    if: github.event.issue.labels.name == 'Client'
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 15 days with no activity. Comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 14
          days-before-close: 7
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  issue_inprogress:
    name: issue_inprogress
    runs-on: ubuntu-latest
    steps:
      - name: Check member
        id: checkUser
        if: github.event_name == 'issue_comment'
        uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
      - name: Moved issue to ${{ env.not_ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'read'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.not_ans }} # Target status
      - name: Delete label from issue
        if: steps.checkUser.outputs.user-permission == 'read'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number="${{ github.event.issue.number }}"
          label_to_delete="Client" # Specify the label you want to delete here
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${issue_number}/labels/${label_to_delete}"
      - name: Moved issue to ${{ env.ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'write' || steps.checkUser.outputs.user-permission == 'admin'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.ans }} # Target status
      - name: Add label to issue
        if: steps.checkUser.outputs.user-permission == 'write' || steps.checkUser.outputs.user-permission == 'admin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number="${{ github.event.issue.number }}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${issue_number}/labels" \
            -d '["Client"]' # Add labels you want here
