name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  issue_comment:
    types: created
  schedule:
    - cron: '20 15 * * *'

# map fields with customized labels
env:
  todo: Todo
  done: Done
  in_progress: In Progress
  ans: Answered
  not_ans: Not Answered
  organization: dev-embention
  project: 2

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }} # New issues
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          #user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  issue_done:
    name: issue_done
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.2.25
        id: get_status
        with:
          query: |
            query {
              organization(login: "dev-embention") {
                 projectV2(number:${{ env.project }}) {
                  ... on ProjectV2 {
                    items(last: 20) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            title
                            url
                            state {
                              ... on IssueState {
                                opened
                              }
                            }
                            assignees(first: 10) {
                              nodes {
                                login
                              }
                            }
                          }
                        }
                        fieldValues(first: 20) {
                          nodes {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              field {
                                ... on ProjectV2SingleSelectField {
                                  name
                                }
                              }
                              name
                              id
                            }
                            ... on ProjectV2ItemFieldLabelValue {
                              labels(first: 20) {
                                nodes {
                                  id
                                  name
                                }
                              }
                            }
                            ... on ProjectV2ItemFieldTextValue {
                              text
                              id
                              updatedAt
                              creator {
                                url
                              }
                            }
                            ... on ProjectV2ItemFieldMilestoneValue {
                              milestone {
                                id
                              }
                            }
                            ... on ProjectV2ItemFieldRepositoryValue {
                              repository {
                                id
                                url
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
      - run: "echo 'latest release: ${{ steps.get_status.outputs.data }}'"
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  issue_inprogress:
    name: issue_inprogress
    runs-on: ubuntu-latest
    steps:
      - name: Check member
        id: checkUser
        if: github.event_name == 'issue_comment'
        uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
      - name: Moved issue to ${{ env.ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'write' || steps.checkUser.outputs.user-permission == 'admin'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.ans }} # Target status
      - name: Moved issue to ${{ env.not_ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'read'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.not_ans }} # Target status
