name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - labeled
  issue_comment:
    types: created
  schedule:
    - cron: '00 16 * * *'

# map fields with customized labels
env:
  todo: Todo
  done: Done
  in_progress: In Progress
  ans: Answered
  not_ans: Not Answered
  organization: dev-embention
  project: 2
  REPO_TITLE: ${{ github.repository }}
  ISSUE_TITLE: "${{ github.event.issue.title }}"
  
jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Support Ticket'
    steps:
      - name: Move issue to ${{ env.todo }} # New issues
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          #user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  issue_stale:
    name: issue_stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        id: build
        with:
          any-of-issue-labels: 'Support Ticket'
          stale-issue-message: 'This issue is stale because it has been open 15 days with no activity. Comment or this will be closed in 7 days.'
          days-before-stale: 1
          remove-issue-stale-when-updated: true
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: github.event.sender.type == 'Bot' && contains(github.event.comment.body, 'stale')
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  issue_done:
    name: issue_done
    runs-on: ubuntu-latest
    steps:
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: contains(github.event.comment.body, 'stale')
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  issue_inprogress:
    name: issue_inprogress
    runs-on: ubuntu-latest
    steps:
      - name: Check member
        id: checkUser
        if: github.event_name == 'issue_comment' && github.event.issue.labels.name == 'Support Ticket'
        uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
      - name: Moved issue to ${{ env.not_ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'read'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.not_ans }} # Target status
      - name: Moved issue to ${{ env.ans }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        if: steps.checkUser.outputs.user-permission == 'write' || steps.checkUser.outputs.user-permission == 'admin'
        with:
          gh_token: ${{ secrets.GH_TOKEN_MOVE_ISSUES }}
          # user: sample-user
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.ans }} # Target status
